# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Studious
email: danielhg52@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This are my school (mechatronic engineering) notes. I study at UPIITA - IPN in Mexico.
baseurl: "/studious"
url: "https://danielhj1998.github.io"
#permalink: /:categories/:slug
github_username:  danielhj1998

# Build
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: true
    math_engine: katex
    syntax_highlighter: rouge
    # The options can be found here: https://katex.org/docs/options.html
    #math_engine_opts:
        #fleqn: false

# Plugins
plugins:
    - jekyll-feed
    - jemoji
    - jekyll-relative-links

# Links
link_to:
    github: https://github.com/danielhj1998/studious
